### PR TITLE
Create Tangible Assets Import

### PR DESCRIPTION
**Pull request by theinfamousrj**
This creates 29 tangible assets in the `generic_asset` table when this SQL script is ran.

### CODE REVIEW

**Comment by theinfamousrj** [comment]
@bacloud14 Let me know what you think about this one and I will continue to create more if this is in the realm of what you want. 😄

**Comment by bacloud14** [comment]
Sur @theinfamousrj  
This is a valuable and sweet addition. Motivated me to put some time on this repo. How do you like the idea by the way? After reading README

**Comment by theinfamousrj** [comment]
It's definitely an interesting repo, something I'm willing to put more time into. I saw it on the Hacktoberfest page and I didn't see anyone helping so, I figured I would. I've done a lot of SQL before but I know nothing about assets at all, so maybe I'll get a chance to learn a thing or two about assets. 😄

**Comment by bacloud14** [comment]
Thank you for showing interest, as you can see, I put things here and there and hope to catch up with someone interested.

**Pull request merged**
